apiVersion: v1
kind: Service
metadata:
  name: {{APP-NAME}}
  namespace: native-ms
#  annotations:
#    cloud.google.com/app-protocols: '{"https":"HTTPS"}'
#    service.beta.kubernetes.io/aws-load-balancer-type: nlb
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: load-balancer-{{APP-NAME}}
