apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-oauth2-server-deployment
  name: oauth2-server
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-oauth2-server-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-oauth2-server-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/nodegroup
                    operator: In
                    values:
                      - staging
      containers:
      - image: $IMAGE
        name: oauth2-server
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources: 
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 256Mi
        env:
          - name: ENVIRONMENT
            value: "staging"
          - name: SPRING_PROFILES_ACTIVE
            value: "staging"
          - name: DB_HOST
            value: "oauth-db.cofk0x2ncce5.us-east-2.rds.amazonaws.com"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "oauth_user"
          - name: DB_PASSWORD
            value: "oauth_pwd"
          - name: KAFKA_PRIMARY_BOOTSTRAP_SERVERS
            value: "pkc-2396y.us-east-1.aws.confluent.cloud:9092"
          - name: KAFKA_PRIMARY_KEY
            value: "X65XBX5JB3E2OSAU"
          - name: KAFKA_PRIMARY_SECRET
            value: "2FAN+OsHiO7X0U+nO9LJvW5pjYmXe4/aGJ7w3KaeHxCojHiD03sd8bnbN+r9iGYP"
          - name: KAFKA_PRIMARY_REQUEST_TIMEOUT_MS
            value: "20000"
          - name: KAFKA_PRIMARY_RETRY_BACKOFF_MS
            value: "500"
          - name: KAFKA_PRIMARY_SCHEMA_REGISTRY_ENDPOINT
            value: "https://psrc-gk071.us-east-2.aws.confluent.cloud"
          - name: KAFKA_PRIMARY_SCHEMA_REGISTRY_KEY
            value: "X4TU3DVAHW7EZUFN"
          - name: KAFKA_PRIMARY_SCHEMA_REGISTRY_SECRET
            value: "QCHklrETPqa2QG99Og3MXsEfzd3aaUddBFI2bUKwTIoqLwC9ccOyPnfBPEz9epga"
        livenessProbe:
          failureThreshold: 18
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 18
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
          
