apiVersion: v1
kind: Service
metadata:
  name: oauth2
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0a9eb08f970cca7ee"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: (https|http|ssl|tcp)
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: load-balancer-oauth2-server-deployment
